language: node_js
node_js:
  - 'stable'
  - '8.4.0'
  - '6.11.2'

cache:
  directories:
    - "node_modules"

before_deploy:
  - zip -r latestTravis *
  - mkdir -p dpl_cd_upload
  - mv latestTravis.zip dpl_cd_upload/latestTravis.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: kcoyner/geogopher
  bucket: gopher-codedeploy
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: gopher-codedeploy
  key: latestTravis.zip
  bundle_type: zip
  application: geogopherApp
  deployment_group: geogopherAppGroup
  region: us-east-1
  on: *2

