language: node_js

cache:
  directories:
    - "node_modules"

before_deploy:
  - zip -r latestTravis *
  - mkdir -p s3_upload
  - mv latestTravis.zip s3_upload/latestTravis.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: s3_upload
  skip_cleanup: true
  on: &2
    repo: kcoyner/geogopher
    branch: travisTuning
  bucket: gopher-codedeploy
  upload-dir: testing
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: gopher-codedeploy
  key: latestTravis.zip
  bundle_type: zip
  application: geogopherApp
  deployment_group: geogopherAppGroup
  region: us-east-1
  on: *2

