version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/geogopher
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
    - location: scripts/delete_old_files.sh
  AfterInstall:
    - location: scripts/sleep.sh
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 45
      runas: root
